DROP TABLE "ZDXM_JEEPLUS"."C_INS_BUSINESS_SSQK";
CREATE TABLE "ZDXM_JEEPLUS"."C_INS_BUSINESS_SSQK"
(
"ID" VARCHAR2(64) NOT NULL,
"CREATE_BY" VARCHAR2(64),
"CREATE_DATE" TIMESTAMP(0),
"UPDATE_BY" VARCHAR2(64),
"UPDATE_DATE" TIMESTAMP(0),
"REMARKS" NVARCHAR2(128),
"DEL_FLAG" VARCHAR2(64),
"XMID" VARCHAR2(64),
"TASK_RELATION_ID" VARCHAR2(64),
"NAME" VARCHAR2(128),
"OFFICE" VARCHAR2(128),
"MOBILE" VARCHAR2(128),
"SJKGSJ" TIMESTAMP(0),
"SJJGSJ" TIMESTAMP(0),
"ZTBXS" VARCHAR2(128),
"SSQKJSDW" VARCHAR2(128),
"SSQKXXJD" VARCHAR2(128),
"SSQKNDJSNR" VARCHAR2(512),
"SSQKWTJJY" VARCHAR2(512),
"SSQKRCJGZJZRDW" VARCHAR2(128),
"SSQKTZJHTZQK" VARCHAR2(128),
"SSQKZFJCJGLXR" VARCHAR2(128),
"SSQKDCJGLXFS" VARCHAR2(128),
"SSQKFGBMLXR" VARCHAR2(128),
"SSQLFGBMLXFS" VARCHAR2(128),
"TYPE" VARCHAR2(64),
"ZYYSNTZLJWCZJ" NUMBER,
"ZYYSNTZLJZFQK" NUMBER,
"ZXZQMJDZXJSZJLJWCZJ" NUMBER,
"ZXZQMJDZXJSZJLJZFQK" NUMBER,
"QTLBHZLJWCZJ" NUMBER,
"QTLBHZLJWCQK" NUMBER,
"ZYYSNTZ_LJDWZJ" NUMBER,
"QTZYCZXJSZJ_LJDWZJ" NUMBER,
"ZXZQMJDZXJSZJ_LJDWZJ" NUMBER,
"ZYSLJSJJ_LJDWZJ" NUMBER,
"NSBDGCJJ_LJDWZJ" NUMBER,
"TLJSZXJJ_LJDWZJ" NUMBER,
"MHFZJJ_LJDWZJ" NUMBER,
"GJZDSLGCJSJJ_LJDWZJ" NUMBER,
"DZXSKYMHQFCJJ_LJDWZJ" NUMBER,
"DZXSKYMHQFCJYJJ_LJDWZJ" NUMBER,
"GLGKJSZXJJ_LJDWZJ" NUMBER,
"SHENGJIYSNTZ_LJDWZJ" NUMBER,
"SHIJIYSNTZ_LJDWZJ" NUMBER,
"XIANJIYSNTZ_LJDWZJ" NUMBER,
"SHENGJICZZJ_LJDWZJ" NUMBER,
"SHIJICZZJ_LJDWZJ" NUMBER,
"XIANJICZZJ_LJDWZJ" NUMBER,
"DFZXJSJJ_LJDWZJ" NUMBER,
"QYZYTZ_LJDWZJ" NUMBER,
"YHDK_LJDWZJ" NUMBER,
"LYWZ_LJDWZJ" NUMBER,
"ZJQDDD_LJDWZJ" NUMBER,
"QTZJ_LJDWZJ" NUMBER,
CONSTRAINT "PK_C_INS_BUSINESS_SSQK_ID" NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

comment on column "ZDXM_JEEPLUS"."C_INS_BUSINESS_SSQK"."ID" is '唯一ID';
comment on column "ZDXM_JEEPLUS"."C_INS_BUSINESS_SSQK"."CREATE_BY" is '创建人';
comment on column "ZDXM_JEEPLUS"."C_INS_BUSINESS_SSQK"."CREATE_DATE" is '创建日期';
comment on column "ZDXM_JEEPLUS"."C_INS_BUSINESS_SSQK"."UPDATE_BY" is '更新人';
comment on column "ZDXM_JEEPLUS"."C_INS_BUSINESS_SSQK"."UPDATE_DATE" is '更新日期';
comment on column "ZDXM_JEEPLUS"."C_INS_BUSINESS_SSQK"."REMARKS" is '备注';
comment on column "ZDXM_JEEPLUS"."C_INS_BUSINESS_SSQK"."DEL_FLAG" is '删除标志';
comment on column "ZDXM_JEEPLUS"."C_INS_BUSINESS_SSQK"."XMID" is '项目基本信息ID';
comment on column "ZDXM_JEEPLUS"."C_INS_BUSINESS_SSQK"."TASK_RELATION_ID" is '调度任务关联表ID';
comment on column "ZDXM_JEEPLUS"."C_INS_BUSINESS_SSQK"."NAME" is '本期调度填报人 姓名';
comment on column "ZDXM_JEEPLUS"."C_INS_BUSINESS_SSQK"."OFFICE" is '本期调度填报人 工作单位';
comment on column "ZDXM_JEEPLUS"."C_INS_BUSINESS_SSQK"."MOBILE" is '本期调度填报人 手机';
comment on column "ZDXM_JEEPLUS"."C_INS_BUSINESS_SSQK"."SJKGSJ" is '实际开工时间';
comment on column "ZDXM_JEEPLUS"."C_INS_BUSINESS_SSQK"."SJJGSJ" is '实际竣工时间';
comment on column "ZDXM_JEEPLUS"."C_INS_BUSINESS_SSQK"."ZTBXS" is '招投标形式';
comment on column "ZDXM_JEEPLUS"."C_INS_BUSINESS_SSQK"."SSQKJSDW" is '建设单位';
comment on column "ZDXM_JEEPLUS"."C_INS_BUSINESS_SSQK"."SSQKXXJD" is '形象进度';
comment on column "ZDXM_JEEPLUS"."C_INS_BUSINESS_SSQK"."SSQKNDJSNR" is '年度建设内容';
comment on column "ZDXM_JEEPLUS"."C_INS_BUSINESS_SSQK"."SSQKWTJJY" is '问题及建议 进展情况及下一步工作安排';
comment on column "ZDXM_JEEPLUS"."C_INS_BUSINESS_SSQK"."SSQKRCJGZJZRDW" is '日常监管直接责任单位';
comment on column "ZDXM_JEEPLUS"."C_INS_BUSINESS_SSQK"."SSQKTZJHTZQK" is '投资计划调整情况';
comment on column "ZDXM_JEEPLUS"."C_INS_BUSINESS_SSQK"."SSQKZFJCJGLXR" is '政府督查机构联系人';
comment on column "ZDXM_JEEPLUS"."C_INS_BUSINESS_SSQK"."SSQKDCJGLXFS" is '联系方式（电话）';
comment on column "ZDXM_JEEPLUS"."C_INS_BUSINESS_SSQK"."SSQKFGBMLXR" is '发改部门联系人';
comment on column "ZDXM_JEEPLUS"."C_INS_BUSINESS_SSQK"."SSQLFGBMLXFS" is '联系方式（电话）';
comment on column "ZDXM_JEEPLUS"."C_INS_BUSINESS_SSQK"."TYPE" is '实施情况类型（1.项目填报 2.调度反馈）';
comment on column "ZDXM_JEEPLUS"."C_INS_BUSINESS_SSQK"."ZYYSNTZLJWCZJ" is '中央预算内投资 累计完成资金';
comment on column "ZDXM_JEEPLUS"."C_INS_BUSINESS_SSQK"."ZYYSNTZLJZFQK" is '中央预算内投资 累计支付情况';
comment on column "ZDXM_JEEPLUS"."C_INS_BUSINESS_SSQK"."ZXZQMJDZXJSZJLJWCZJ" is '专项债券募集的专项建设资金 累计完成资金';
comment on column "ZDXM_JEEPLUS"."C_INS_BUSINESS_SSQK"."ZXZQMJDZXJSZJLJZFQK" is '专项债券募集的专项建设资金 累计支付情况';
comment on column "ZDXM_JEEPLUS"."C_INS_BUSINESS_SSQK"."QTLBHZLJWCZJ" is '其他类别汇总 累计完成资金';
comment on column "ZDXM_JEEPLUS"."C_INS_BUSINESS_SSQK"."QTLBHZLJWCQK" is '其他类别汇总 累计支付情况';
comment on column "ZDXM_JEEPLUS"."C_INS_BUSINESS_SSQK"."ZYYSNTZ_LJDWZJ" is '中央预算内投资 累计到位资金';
comment on column "ZDXM_JEEPLUS"."C_INS_BUSINESS_SSQK"."QTZYCZXJSZJ_LJDWZJ" is '其他中央财政性建设资金 累计到位资金';
comment on column "ZDXM_JEEPLUS"."C_INS_BUSINESS_SSQK"."ZXZQMJDZXJSZJ_LJDWZJ" is '专项债券募集的专项建设资金 累计到位资金';
comment on column "ZDXM_JEEPLUS"."C_INS_BUSINESS_SSQK"."ZYSLJSJJ_LJDWZJ" is '中央水利建设基金 累计到位资金';
comment on column "ZDXM_JEEPLUS"."C_INS_BUSINESS_SSQK"."NSBDGCJJ_LJDWZJ" is '南水北调工程基金 累计到位资金';
comment on column "ZDXM_JEEPLUS"."C_INS_BUSINESS_SSQK"."TLJSZXJJ_LJDWZJ" is '铁路建设专项基金 累计到位资金';
comment on column "ZDXM_JEEPLUS"."C_INS_BUSINESS_SSQK"."MHFZJJ_LJDWZJ" is '民航发展基金 累计到位资金';
comment on column "ZDXM_JEEPLUS"."C_INS_BUSINESS_SSQK"."GJZDSLGCJSJJ_LJDWZJ" is '国际重大水利工程建设基金 累计到位资金';
comment on column "ZDXM_JEEPLUS"."C_INS_BUSINESS_SSQK"."DZXSKYMHQFCJJ_LJDWZJ" is '大中型水库移民后期扶持基金 累计到位资金';
comment on column "ZDXM_JEEPLUS"."C_INS_BUSINESS_SSQK"."DZXSKYMHQFCJYJJ_LJDWZJ" is '大中型水库移民后期扶持结余基金 累计到位资金';
comment on column "ZDXM_JEEPLUS"."C_INS_BUSINESS_SSQK"."GLGKJSZXJJ_LJDWZJ" is '公路港口建设专项基金 累计到位资金';
comment on column "ZDXM_JEEPLUS"."C_INS_BUSINESS_SSQK"."SHENGJIYSNTZ_LJDWZJ" is '省级预算内投资 累计到位资金';
comment on column "ZDXM_JEEPLUS"."C_INS_BUSINESS_SSQK"."SHIJIYSNTZ_LJDWZJ" is '市级预算内投资 累计到位资金';
comment on column "ZDXM_JEEPLUS"."C_INS_BUSINESS_SSQK"."XIANJIYSNTZ_LJDWZJ" is '县级预算内投资 累计到位资金';
comment on column "ZDXM_JEEPLUS"."C_INS_BUSINESS_SSQK"."SHENGJICZZJ_LJDWZJ" is '省级财政资金 累计到位资金';
comment on column "ZDXM_JEEPLUS"."C_INS_BUSINESS_SSQK"."SHIJICZZJ_LJDWZJ" is '市级财政资金 累计到位资金';
comment on column "ZDXM_JEEPLUS"."C_INS_BUSINESS_SSQK"."XIANJICZZJ_LJDWZJ" is '县级财政资金 累计到位资金';
comment on column "ZDXM_JEEPLUS"."C_INS_BUSINESS_SSQK"."DFZXJSJJ_LJDWZJ" is '地方专项建设基金 累计到位资金';
comment on column "ZDXM_JEEPLUS"."C_INS_BUSINESS_SSQK"."QYZYTZ_LJDWZJ" is '企业自由投资 累计到位资金';
comment on column "ZDXM_JEEPLUS"."C_INS_BUSINESS_SSQK"."YHDK_LJDWZJ" is '银行贷款 累计到位资金';
comment on column "ZDXM_JEEPLUS"."C_INS_BUSINESS_SSQK"."LYWZ_LJDWZJ" is '利用外资 累计到位资金';
comment on column "ZDXM_JEEPLUS"."C_INS_BUSINESS_SSQK"."ZJQDDD_LJDWZJ" is '资金渠道待定 累计到位资金';
comment on column "ZDXM_JEEPLUS"."C_INS_BUSINESS_SSQK"."QTZJ_LJDWZJ" is '其他资金 累计到位资金';
