alter table "ZDXM_JEEPLUS"."XMJBXX" modify "NDZHJSNR" VARCHAR2(2000);
alter table "ZDXM_JEEPLUS"."XMJBXX" modify "TJQK" VARCHAR2(2000);

alter table "ZDXM_JEEPLUS"."C_INS_BUSINESS_LOG" alter column "OPERATE_TYPE" rename to "TYPE";
alter table "ZDXM_JEEPLUS"."C_INS_BUSINESS_LOG" modify "TYPE" VARCHAR2(50);

CREATE TABLE "ZDXM_JEEPLUS"."C_INS_BUSINESS_LOG"
(
"ID" VARCHAR2(64) NOT NULL,
"CREATE_BY" VARCHAR2(64),
"CREATE_DATE" TIMESTAMP(0),
"UPDATE_BY" VARCHAR2(64),
"UPDATE_DATE" TIMESTAMP(0),
"REMARKS" VARCHAR2(512),
"DEL_FLAG" VARCHAR2(64),
"OBJECT_ID" VARCHAR2(64),
"OBJECT_NAME" VARCHAR2(64),
"OPERATE_USER_ID" VARCHAR2(64),
"OPERATE_DEPT_ID" VARCHAR2(64),
"RECEIVE_USER_ID" VARCHAR2(64),
"RECEIVE_DEPT_ID" VARCHAR2(64),
"RECEIVE_OFFICE_ID" VARCHAR2(64),
"OPERATE" VARCHAR2(128),
"TYPE" VARCHAR2(50),
"OPERATE_USER_NAME" CHAR(128),
"OPERATE_DEPT_NAME" CHAR(128),
"RECEIVE_DEPT_NAME" CHAR(128),
CONSTRAINT "PK_C_INS_BUSINESS_LOG_ID" NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "WEBSITE", CLUSTERBTR) ;


alter table "ZDXM_JEEPLUS"."C_INS_BUSINESS_LOG" add column("OPERATE_USER_NAME" CHAR(128));
comment on column "ZDXM_JEEPLUS"."C_INS_BUSINESS_LOG"."OPERATE_USER_NAME" is '操作人名称（因为一带一路网站记录用户没有同步过来）';
alter table "ZDXM_JEEPLUS"."C_INS_BUSINESS_LOG" add column("OPERATE_DEPT_NAME" CHAR(128));
comment on column "ZDXM_JEEPLUS"."C_INS_BUSINESS_LOG"."OPERATE_DEPT_NAME" is '操作部门ID（因为一带一路网站记录部门没有同步过来）';
alter table "ZDXM_JEEPLUS"."C_INS_BUSINESS_LOG" add column("RECEIVE_DEPT_NAME" CHAR(128));
comment on column "ZDXM_JEEPLUS"."C_INS_BUSINESS_LOG"."RECEIVE_DEPT_NAME" is '接收处室名称';