-- 添加项目调度信息表
CREATE TABLE "ZDXM_JEEPLUS"."C_INS_BUSINESS_SCHEDULER_TASK"
(
"ID" VARCHAR2(64) NOT NULL,
"CREATE_BY" VARCHAR2(64),
"CREATE_DATE" TIMESTAMP(0),
"UPDATE_BY" VARCHAR2(64),
"UPDATE_DATE" TIMESTAMP(0),
"REMARKS" NVARCHAR2(255),
"DEL_FLAG" VARCHAR2(64),
"NAME" VARCHAR2(128),
"TYPE" VARCHAR2(128),
"START_DATE" TIMESTAMP(0),
"END_DATE" TIMESTAMP(0),
"REQUIREMENT" VARCHAR2(512),
"ORIGIN" VARCHAR2(128),
"ISSUE_DATE" TIMESTAMP(0),
"DEPT_ID" VARCHAR2(64),
CONSTRAINT "PK_C_INS_BUSINESS_SCHEDULER_TASK_ID" NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

-- 添加项目-调度关联表
CREATE TABLE "ZDXM_JEEPLUS"."C_INS_BUSINESS_XMJBXX_TASK_RELATION"
(
"ID" VARCHAR2(64) NOT NULL,
"CREATE_BY" VARCHAR2(64),
"CREATE_DATE" TIMESTAMP(0),
"UPDATE_BY" VARCHAR2(64),
"UPDATE_DATE" TIMESTAMP(0),
"REMARKS" VARCHAR2(255),
"DEL_FLAG" VARCHAR2(64),
"XMJBXX_ID" VARCHAR2(64),
"TASK_ID" VARCHAR2(64),
"STATUS" VARCHAR2(64),
"FINISH_DATE" TIMESTAMP(0),
"FEEDBACK" VARCHAR2(512),
"DEST_DEPT_ID" VARCHAR2(64),
CONSTRAINT "PK_C_INS_BUSINESS_XMJBXX_TASK_RELATION_ID" NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;

-- 修改【调度任务执行】的菜单名为【调度任务管理】
update sys_menu set name = '调度任务管理' where name = '调度任务执行';

-- 更新 撒年滚动计划的报送状态为未报送
update c_ins_business_xmjbxx_dept_relation set bszt = '0' where type = '3' and bszt is null;