CREATE TABLE "ZDXM_JEEPLUS"."C_INS_BUSINESS_XMJBXX_DEPT_RELATION"
(
  "ID" VARCHAR2(64) NOT NULL,
  "CREATE_BY" VARCHAR2(64),
  "CREATE_DATE" TIMESTAMP(0),
  "UPDATE_BY" VARCHAR2(64),
  "UPDATE_DATE" TIMESTAMP(0),
  "REMARKS" NVARCHAR2(255),
  "DEL_FLAG" VARCHAR2(64),
  "XMJBXX_ID" VARCHAR2(64),
  "DEPT_ID" VARCHAR2(64),
  "TYPE" VARCHAR2(64),
  CONSTRAINT "PK_C_INS_BUSINESS_XMJBXX_DEPT_RELATION_ID" NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "MAIN", CLUSTERBTR) ;